[package]
name = "stellar-vpn-desktop"
version = "0.1.0"
description = "Stellar VPN Desktop"
authors = ["Stellar Security"]
edition = "2021"

[dependencies]
tauri = { version = "2.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tauri-plugin-store = "2.4.1"

reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }
url = "2"
sha2 = "0.10"
hex = "0.4"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }


